### PR TITLE
Bug 1316668 - Re-add devtools looking and make it better

### PR DESCRIPTION
**Pull request by denschub**
Sorry that this contains two changes in one PR - I already spent quite some time with splitting off other parts, and there was no way I can sensibly not PR these two at the same time (I'd go into rebasing hell for that one, so...)

---

After a long and hard journey (of which I should write a book about), here is a PR that looks like 10 minutes of work. :) Basically, this uses `nsIConsoleService` to send a custom message to the console. Also, I added the option of adding a link to the contents, since we need that one anyway.

I may change the format again later, I am currently playing around with a possible way to make the link actually clickable. But if this gets reviewed by @MDTsai before I finished that, I'll follow up. For now, I just want to have this merged.

r? @MDTsai

### CODE REVIEW

**Comment by miketaylr** [comment]
Ping @MDTsai

**Comment by MDTsai** [comment]
@denschub I think you need a update for this? 
```
DenSchub> etsai: hold back with the review for one more day -- i want to push another thing. i thought i could finish it tonight, but it's 1am now and i'm too tired. i'll ping you tomorrow. :)
```

**Comment by miketaylr** [comment]
(oops, sorry looks like i was butting in :P)

**Comment by miketaylr** [comment]
> hold back with the review for one more day -- i want to push another thing.

@denschub did you forget to push this thing?

**Comment by denschub** [comment]
> did you forget to push this thing?

No, I don't. it ended up regressing perf tests, then I ended up fixing quantum startup, then other work happened, then I closed this PR by accident. Reopening and noting that this is on top of my stack after landing the fixes.

**Comment by denschub** [comment]
Deprecated, a new PR will be opened soon.

**Pull request closed without merging**
